@file:OptIn(UnsafeDuringIrConstructionAPI::class)
package yairm210.purity.validation

import org.jetbrains.kotlin.ir.declarations.*
import org.jetbrains.kotlin.ir.expressions.*
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.util.*
import org.jetbrains.kotlin.name.FqName
import yairm210.purity.PurityConfig
import yairm210.purity.validation.wellknown.*

/** Checks the expected purity of a given IrFunction.
 * Unlike [CheckFunctionPurityVisitor] this is not a deep dive into the function.
 * Rather, it checks by annotations, function names, and parent classes. 
 * */
object ExpectedFunctionPurityChecker {
    
    private val intrinsicConstEvaluationFqName = FqName("kotlin.internal.IntrinsicConstEvaluation")

    /** Tests shallowly whether we should consider the function as pure.
     * Does not check the function body, but rather checks for annotations, function names, and parent classes.
     * */
    fun isMarkedAsPure(function: IrFunction, purityConfig: PurityConfig): Boolean {
        // Marked by @Pure, well-known FQN (built-in or user config), or overrides a function that is
        if (FunctionAnnotations.Pure.isExplicitlyMarked(function, purityConfig)) return true

        // Simple values like int + int -> plus(int, int), are marked thus
        val constEvaluation = function.getAnnotation(intrinsicConstEvaluationFqName)
        if (constEvaluation != null) return true

        val fullyQualifiedFunctionName = function.fqNameForIrSerialization.asString()
        if (wellKnownPureFunctionsPrefixes.any { fullyQualifiedFunctionName.startsWith(it) }) return true

        // autogenerated <get-val> functions for files & classes - allows reading from class.val
        if (function.isGetter
            && !(function as IrSimpleFunction).correspondingPropertySymbol!!.owner.isVar
        ) return true

        if (function is IrSimpleFunction) {
            for (overriddenFunction in getAllOverriddenFunctions(function).toSet()) {
                val overriddenFunctionName = overriddenFunction.fqNameForIrSerialization.asString()
                if (wellKnownPureFunctionsPrefixes.any { overriddenFunctionName.startsWith(it) }) return true
            }
        }

        if (isSingleStatementReturnPure(function)) return true

        if (isAutogeneratedEnumFunction(function)) return true

        if (isOfImmutableDataClass(function) && isAutogeneratedDataClassFunction(function)) return true

        return false
    }
    
    private val autogeneratedEnumFunctionNames = setOf("values", "valueOf", "compareTo")
    private fun isAutogeneratedEnumFunction(function: IrFunction): Boolean {
        if ((function.parent as? IrClass)?.isEnumClass != true) return false
        return function.name.asString() in autogeneratedEnumFunctionNames
    }
    
    private fun isOfImmutableDataClass(function: IrFunction): Boolean {
        val parentClass = function.parent as? IrClass ?: return false
        if (!parentClass.isData) return false
        return parentClass.properties.none { it.isVar }
    }
    
    fun isOfDataClass(function: IrFunction): Boolean {
        val parentClass = function.parent as? IrClass ?: return false
        return parentClass.isData
    }

    /** Regex for data class componentN functions */
    val componentRegex = "component\\d+".toRegex()
    
    private fun isAutogeneratedDataClassFunction(function: IrFunction): Boolean {
        if (function.name.asString() == "copy") return true // copy function for data classes
        if (function.name.asString().matches(componentRegex)) return true // componentN functions for data classes
        return false
    }


    fun isReadonly(function: IrFunction, purityConfig: PurityConfig): Boolean {
        if (function.isGetter) return true

        // Marked by @Readonly, well-known FQN (built-in or user config), or overrides a function that is
        if (FunctionAnnotations.Readonly.isExplicitlyMarked(function, purityConfig)) return true

        if (function.name.asString().startsWith("<get-")) return true // Autogenerated function for class variables

        // Do NOT check for readonly parent classes - child classes can add non-readonly functionality!
        // E.g. List is readonly, but ArrayList is not.

        if (isSingleStatementReturnReadonly(function)) return true

        // Data class destructuring functions
        if (isOfDataClass(function) && isAutogeneratedDataClassFunction(function)) return true

        return false
    }

    /** For convenience - single-declaration functions like "fun getX() = x" are readonly */
    private fun isSingleStatementReturnReadonly(function: IrFunction): Boolean {
        val body = function.body ?: return false
        if (body is IrSyntheticBody) return false // Not sure what this IS, but it has no statements
        if (body.statements.size != 1) return false
        val statement = body.statements[0]
        if (statement !is IrReturn) return false
        val value = statement.value

        if (value is IrGetValue) return true // function local variable access
        
        // getter for a field e.g. this.varvar
        if (value is IrCall && value.symbol.owner.isGetter // <something>.property
            && value.dispatchReceiver is IrGetValue  // <something> is a function local variable
         ) return true

        return false
    }

    private fun isSingleStatementReturnPure(function: IrFunction): Boolean {
        val body = function.body ?: return false
        if (body is IrSyntheticBody) return false // Not sure what this IS, but it has no statements
        if (body.statements.size != 1) return false
        val statement = body.statements[0]
        if (statement !is IrReturn) return false

        val value = statement.value
        if (value is IrConst) return true
        if (value is IrGetValue && !value.symbol.owner.let { it is IrVariable && it.isVar }) return true
        
        if (value is IrCall && value.symbol.owner.isGetter && // <something>.property 
            value.dispatchReceiver is IrGetValue  // <something> is a function-local value, not variable
                && !(value.dispatchReceiver as IrGetValue).symbol.owner.let { it is IrVariable && it.isVar }
                && value.symbol.owner.correspondingPropertySymbol?.owner?.isVar == false) return true

        return false
    }
}

// overriddenSymbols only gives you the *direct* overrides, not the transitive ones.
internal fun getAllOverriddenFunctions(function: IrSimpleFunction): Sequence<IrSimpleFunction> {
    return function.overriddenSymbols.asSequence()
        .flatMap {
            val owner = it.owner
            sequenceOf(owner) + getAllOverriddenFunctions(owner)
        }
}
