@file:OptIn(UnsafeDuringIrConstructionAPI::class)
package yairm210.purity.validation

import org.jetbrains.kotlin.cli.common.messages.CompilerMessageSeverity
import org.jetbrains.kotlin.cli.common.messages.MessageCollector
import org.jetbrains.kotlin.ir.IrElement
import org.jetbrains.kotlin.ir.declarations.IrAnnotationContainer
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrFunction
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrVariable
import org.jetbrains.kotlin.ir.expressions.IrCall
import org.jetbrains.kotlin.ir.expressions.IrConstructorCall
import org.jetbrains.kotlin.ir.expressions.IrGetValue
import org.jetbrains.kotlin.ir.expressions.IrReturn
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.util.*
import org.jetbrains.kotlin.ir.visitors.IrVisitor
import org.jetbrains.kotlin.name.FqName
import yairm210.purity.PurityConfig
import yairm210.purity.validation.wellknown.wellKnownInternalStateClasses
import yairm210.purity.validation.wellknown.wellKnownNewInstanceFunctions
import yairm210.purity.validation.wellknown.wellKnownPureClasses
import yairm210.purity.validation.wellknown.wellKnownPureFunctions
import yairm210.purity.validation.wellknown.wellKnownReadonlyClasses
import yairm210.purity.validation.wellknown.wellKnownReadonlyFunctions

/**
 * Unifies, for each purity-related annotation, the four things every one of them needs:
 *  A. [fqName] - the annotation's FqName
 *  B. the user-configured well-known function/class names for it (from [PurityConfig])
 *  C. [isExplicitlyMarked] - is a function marked as this annotation - directly, via well-known FQN
 *     (built-in or user config), because it overrides a function that is, or because its class is
 *     marked (directly, or via well-known FQN)
 *  D. [validate] - given a function marked/expected to be this annotation, check that its body
 *     actually follows the annotation's rules, reporting + returning any violations
 *
 * Only [ModifiesInternalStateOnly] can actually be placed on a class as an annotation (`@Target` on
 * the others is function-only) - but all four entries support marking a *whole class* via the
 * well-known-classes FQN config, meaning "every function of this class is marked".
 *
 * Note: [isExplicitlyMarked] only covers the mechanical annotation/FQN/override/class matching that is
 * common to all of these. @Pure and @Readonly have additional structural heuristics layered on top of
 * this (autogenerated functions, single-statement returns, etc.) in [ExpectedFunctionPurityChecker] -
 * isExplicitlyMarked is the shared core those build on, not the full story for those two.
 */
enum class FunctionAnnotations(
    val fqName: FqName,
    private val wellKnownFunctions: Set<String>,
    private val wellKnownFunctionsFromUser: (PurityConfig) -> Set<String>,
    // Class-level marking doesn't apply to every annotation (e.g. a class can't sensibly be marked
    // "returns a new instance" as a whole) - defaults to "no class-level support" for those that don't need it
    private val wellKnownClasses: Set<String> = emptySet(),
    private val wellKnownClassesFromUser: (PurityConfig) -> Set<String> = { emptySet() },
    // Deprecated alias also recognized for backward compatibility - e.g. @InternalState for ModifiesInternalStateOnly
    private val legacyFqName: FqName? = null,
) {
    Pure(
        Annotations.Pure,
        wellKnownPureFunctions,
        { it.wellKnownPureFunctionsFromUser },
        wellKnownPureClasses,
        { it.wellKnownPureClassesFromUser },
    ) {
        override fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String> {
            val visitor = CheckFunctionPurityVisitor(function, FunctionPurity.Pure, messageCollector, purityConfig)
            function.accept(visitor, Unit)
            return visitor.reportedMessages
        }
    },

    Readonly(
        Annotations.Readonly,
        wellKnownReadonlyFunctions,
        { it.wellKnownReadonlyFunctionsFromUser },
        wellKnownReadonlyClasses,
        { it.wellKnownReadonlyClassesFromUser },
    ) {
        override fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String> {
            val visitor = CheckFunctionPurityVisitor(function, FunctionPurity.Readonly, messageCollector, purityConfig)
            function.accept(visitor, Unit)
            return visitor.reportedMessages
        }
    },

    ReturnsNewInstance(
        Annotations.ReturnsNewInstance,
        wellKnownNewInstanceFunctions,
        { it.wellKnownNewInstanceFunctionsFromUser },
        // No class-level marking - "this whole class returns new instances" doesn't make sense as a concept
    ) {
        override fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String> =
            validateReturnsNewInstance(function, purityConfig, messageCollector)
    },

    ModifiesInternalStateOnly(
        Annotations.ModifiesInternalStateOnly,
        emptySet(),
        { it.wellKnownModifiesInternalStateOnlyFunctionsFromUser },
        wellKnownInternalStateClasses,
        { it.wellKnownInternalStateClassesFromUser },
        legacyFqName = Annotations.InternalState,
    ) {
        override fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String> =
            validateModifiesInternalStateOnly(function, purityConfig, messageCollector)
    };

    private fun IrAnnotationContainer.hasThisOrLegacyAnnotation(): Boolean =
        hasAnnotation(fqName) || (legacyFqName != null && hasAnnotation(legacyFqName))

    /** Is [irClass] marked as this annotation - directly, or via well-known FQN (built-in or user config). */
    private fun isClassMarked(irClass: IrClass, purityConfig: PurityConfig): Boolean {
        if (irClass.hasThisOrLegacyAnnotation()) return true
        val fqn = irClass.fqNameForIrSerialization.asString()
        if (fqn in wellKnownClasses) return true
        if (fqn in wellKnownClassesFromUser(purityConfig)) return true
        return false
    }

    /** Is [function] marked as this annotation - directly, via well-known FQN (built-in or user config),
     * because it overrides a function that is, or because its class is marked (directly, or via well-known FQN). */
    fun isExplicitlyMarked(function: IrFunction, purityConfig: PurityConfig): Boolean {
        if (function.hasThisOrLegacyAnnotation()) return true

        val fqn = function.fqNameForIrSerialization.asString()
        if (fqn in wellKnownFunctions) return true
        if (fqn in wellKnownFunctionsFromUser(purityConfig)) return true

        val parentClass = function.parentClassOrNull
        if (parentClass != null && isClassMarked(parentClass, purityConfig)) return true

        if (function is IrSimpleFunction) {
            for (overriddenFunction in getAllOverriddenFunctions(function)) {
                if (overriddenFunction.hasThisOrLegacyAnnotation()) return true
                val overriddenFqn = overriddenFunction.fqNameForIrSerialization.asString()
                if (overriddenFqn in wellKnownFunctions) return true
                if (overriddenFqn in wellKnownFunctionsFromUser(purityConfig)) return true
                val overriddenParentClass = overriddenFunction.parentClassOrNull
                if (overriddenParentClass != null && isClassMarked(overriddenParentClass, purityConfig)) return true
            }
        }
        return false
    }

    /** Checks that [function], expected to follow this annotation's rules, actually does -
     * reports any violations via [messageCollector] (respecting @TestExpectCompileError) and
     * returns the reported messages (empty if valid). */
    abstract fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String>
}

/** Builds a suggestion for how to make [calledFunction] recognized as always returning a new instance -
 * annotating it directly if it's part of this compilation and its body already satisfies the rule
 * (checked hypothetically, regardless of whether it's currently annotated/well-known), or declaring
 * it via the FQN config otherwise. Returns null if the function is part of this compilation but its
 * body demonstrably does NOT satisfy the rule - annotating it would just cause a new compile error,
 * and asserting it via the FQN config would be asserting something false, so no suggestion is safe. */
fun suggestReturnsNewInstanceFix(calledFunction: IrFunction, purityConfig: PurityConfig): String? {
    val calledFunctionFqName = calledFunction.fqNameForIrSerialization.asString()
    // A function has an accessible body only if it's part of the current compilation - external/stdlib
    // functions (e.g. kotlin.text.split) are deserialized without one, so we can't annotate or validate them
    val isCompilationAvailable = calledFunction.body != null
    return when {
        !isCompilationAvailable ->
            " - If \"$calledFunctionFqName\" always returns a freshly allocated instance not aliased elsewhere, " +
                "you can add \"$calledFunctionFqName\" to wellKnownNewInstanceFunctions via the PurityConfiguration in gradle - " +
                "see https://yairm210.github.io/Purity/usage/advanced-usage/#marking-functions-as-returning-a-new-instance \n"
        checkReturnsNewInstanceBody(calledFunction, purityConfig).isEmpty() ->
            " - You can annotate \"$calledFunctionFqName\" as @ReturnsNewInstance - " +
                "see https://yairm210.github.io/Purity/usage/advanced-usage/#marking-functions-as-returning-a-new-instance \n"
        else -> null
    }
}

/** A @ReturnsNewInstance function (or override of one) must only return: a constructor call, a call to
 * another @ReturnsNewInstance function, or a local val that was itself assigned from one of those. */
private fun validateReturnsNewInstance(
    function: IrFunction,
    purityConfig: PurityConfig,
    messageCollector: MessageCollector,
): List<String> {
    if (!FunctionAnnotations.ReturnsNewInstance.isExplicitlyMarked(function, purityConfig)) return emptyList()

    val errorSeverity = if (function.hasAnnotation(Annotations.TestExpectCompileError)) CompilerMessageSeverity.WARNING else CompilerMessageSeverity.ERROR
    val messages = mutableListOf<String>()

    for ((message, element) in checkReturnsNewInstanceBody(function, purityConfig)) {
        messageCollector.report(errorSeverity, message, getLocationForExpression(function, element))
        messages.add(message)
    }
    return messages
}

/** Checks [function]'s body against the @ReturnsNewInstance rule, regardless of whether it is
 * currently marked/known as such - i.e. "would this pass if annotated?". Returns one
 * (message, offending IrReturn) pair per violation. */
private fun checkReturnsNewInstanceBody(
    function: IrFunction,
    purityConfig: PurityConfig,
): List<Pair<String, IrElement>> {
    val ownedInstances = OwnedInstanceVariableTracker(purityConfig)
    val violations = mutableListOf<Pair<String, IrElement>>()

    val visitor = object : IrVisitor<Unit, Unit>() {
        override fun visitVariable(declaration: IrVariable, data: Unit) {
            ownedInstances.visitVariable(declaration)
            super.visitVariable(declaration, data)
        }

        override fun visitReturn(expression: IrReturn, data: Unit) {
            if (expression.returnTargetSymbol == function.symbol) {
                val value = unwrapSafeCall(expression.value)
                val isNewInstance = when (value) {
                    is IrConstructorCall -> true
                    is IrCall -> FunctionAnnotations.ReturnsNewInstance.isExplicitlyMarked(value.symbol.owner, purityConfig)
                    is IrGetValue -> ownedInstances.isOwned(value)
                    else -> false
                }
                if (!isNewInstance) {
                    var message = "Function \"${function.name}\" is marked as (or overrides a function marked as) @ReturnsNewInstance " +
                        "but returns a value that is not a constructor call, a call to another @ReturnsNewInstance function, " +
                        "or a local val assigned from one of those.\n"

                    // If the returned value is itself a function call, suggest how to make that function
                    // recognized as returning a new instance too, so it can be used here directly
                    if (value is IrCall) {
                        suggestReturnsNewInstanceFix(value.symbol.owner, purityConfig)?.let { message += it }
                    }

                    violations.add(message to expression)
                }
            }
            super.visitReturn(expression, data)
        }

        override fun visitElement(element: IrElement, data: Unit) {
            element.acceptChildren(this, data)
        }
    }
    function.accept(visitor, Unit)
    return violations
}

