@file:OptIn(UnsafeDuringIrConstructionAPI::class)
package yairm210.purity.validation

import org.jetbrains.kotlin.cli.common.messages.MessageCollector
import org.jetbrains.kotlin.ir.declarations.IrAnnotationContainer
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrFunction
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.util.*
import org.jetbrains.kotlin.name.FqName
import yairm210.purity.PurityConfig
import yairm210.purity.validation.functionpurity.CheckFunctionPurityVisitor
import yairm210.purity.validation.functionpurity.FunctionPurity
import yairm210.purity.validation.functionpurity.wellknown.wellKnownPureClasses
import yairm210.purity.validation.functionpurity.wellknown.wellKnownPureFunctions
import yairm210.purity.validation.functionpurity.wellknown.wellKnownReadonlyClasses
import yairm210.purity.validation.functionpurity.wellknown.wellKnownReadonlyFunctions
import yairm210.purity.validation.internalstateaccess.validateInternalStateAccess
import yairm210.purity.validation.internalstatemutation.wellknown.wellKnownInternalStateClasses
import yairm210.purity.validation.internalstatemutation.validateInternalStateMutation
import yairm210.purity.validation.returnsnewinstance.validateReturnsNewInstance
import yairm210.purity.validation.returnsnewinstance.wellknown.wellKnownNewInstanceFunctions

/**
 * Unifies, for each purity-related annotation, the four things every one of them needs:
 *  A. [fqName] - the annotation's FqName
 *  B. the user-configured well-known function/class names for it (from [PurityConfig])
 *  C. [isExplicitlyMarked] - is a function marked as this annotation - directly, via well-known FQN
 *     (built-in or user config), because it overrides a function that is, or because its class is
 *     marked (directly, or via well-known FQN)
 *  D. [validate] - given a function marked/expected to be this annotation, check that its body
 *     actually follows the annotation's rules, reporting + returning any violations
 *
 * Only [InternalStateMutation] and [InternalStateAccess] can actually be placed on a class as an
 * annotation (`@Target` on the others is function-only) - but every entry supports marking a
 * *whole class* via the well-known-classes FQN config, meaning "every function of this class is marked".
 *
 * Note: [isExplicitlyMarked] only covers the mechanical annotation/FQN/override/class matching that is
 * common to all of these. @Pure and @Readonly have additional structural heuristics layered on top of
 * this (autogenerated functions, single-statement returns, etc.) in [ExpectedFunctionPurityChecker] -
 * isExplicitlyMarked is the shared core those build on, not the full story for those two.
 */
enum class FunctionAnnotations(
    val fqName: FqName,
    private val wellKnownFunctions: Set<String>,
    private val wellKnownFunctionsFromUser: (PurityConfig) -> Set<String>,
    // Class-level marking doesn't apply to every annotation (e.g. a class can't sensibly be marked
    // "returns a new instance" as a whole) - defaults to "no class-level support" for those that don't need it
    private val wellKnownClasses: Set<String> = emptySet(),
    private val wellKnownClassesFromUser: (PurityConfig) -> Set<String> = { emptySet() },
    // Deprecated alias also recognized for backward compatibility - e.g. @InternalState for InternalStateMutation
    private val legacyFqName: FqName? = null,
) {
    Pure(
        Annotations.Pure,
        wellKnownPureFunctions,
        { it.wellKnownPureFunctionsFromUser },
        wellKnownPureClasses,
        { it.wellKnownPureClassesFromUser },
    ) {
        override fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String> {
            val visitor = CheckFunctionPurityVisitor(function, FunctionPurity.Pure, messageCollector, purityConfig)
            function.accept(visitor, Unit)
            return visitor.reportedMessages
        }
    },

    Readonly(
        Annotations.Readonly,
        wellKnownReadonlyFunctions,
        { it.wellKnownReadonlyFunctionsFromUser },
        wellKnownReadonlyClasses,
        { it.wellKnownReadonlyClassesFromUser },
    ) {
        override fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String> {
            val visitor = CheckFunctionPurityVisitor(function, FunctionPurity.Readonly, messageCollector, purityConfig)
            function.accept(visitor, Unit)
            return visitor.reportedMessages
        }
    },

    ReturnsNewInstance(
        Annotations.ReturnsNewInstance,
        wellKnownNewInstanceFunctions,
        { it.wellKnownNewInstanceFunctionsFromUser },
        // No class-level marking - "this whole class returns new instances" doesn't make sense as a concept
    ) {
        override fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String> =
            validateReturnsNewInstance(function, purityConfig, messageCollector)
    },

    InternalStateMutation(
        Annotations.InternalStateMutation,
        emptySet(),
        { it.wellKnownInternalStateMutationFunctionsFromUser },
        wellKnownInternalStateClasses,
        { it.wellKnownInternalStateClassesFromUser },
        legacyFqName = Annotations.InternalState,
    ) {
        override fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String> =
            validateInternalStateMutation(function, purityConfig, messageCollector)
    },

    InternalStateAccess(
        Annotations.InternalStateAccess,
        emptySet(),
        { it.wellKnownInternalStateAccessFunctionsFromUser },
    ) {
        override fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String> =
            validateInternalStateAccess(function, purityConfig, messageCollector)
    };

    private fun IrAnnotationContainer.hasThisOrLegacyAnnotation(): Boolean =
        hasAnnotation(fqName) || (legacyFqName != null && hasAnnotation(legacyFqName))

    /** Is [irClass] marked as this annotation - directly, or via well-known FQN (built-in or user config). */
    private fun isClassMarked(irClass: IrClass, purityConfig: PurityConfig): Boolean {
        if (irClass.hasThisOrLegacyAnnotation()) return true
        val fqn = irClass.fqNameForIrSerialization.asString()
        if (fqn in wellKnownClasses) return true
        if (fqn in wellKnownClassesFromUser(purityConfig)) return true
        return false
    }

    /** Is [function] marked as this annotation - directly, via well-known FQN (built-in or user config),
     * because it overrides a function that is, or because its class is marked (directly, or via well-known FQN). */
    fun isExplicitlyMarked(function: IrFunction, purityConfig: PurityConfig): Boolean {
        if (function.hasThisOrLegacyAnnotation()) return true

        val fqn = function.fqNameForIrSerialization.asString()
        if (fqn in wellKnownFunctions) return true
        if (fqn in wellKnownFunctionsFromUser(purityConfig)) return true

        val parentClass = function.parentClassOrNull
        if (parentClass != null && isClassMarked(parentClass, purityConfig)) return true

        if (function is IrSimpleFunction) {
            for (overriddenFunction in getAllOverriddenFunctions(function)) {
                if (overriddenFunction.hasThisOrLegacyAnnotation()) return true
                val overriddenFqn = overriddenFunction.fqNameForIrSerialization.asString()
                if (overriddenFqn in wellKnownFunctions) return true
                if (overriddenFqn in wellKnownFunctionsFromUser(purityConfig)) return true
                val overriddenParentClass = overriddenFunction.parentClassOrNull
                if (overriddenParentClass != null && isClassMarked(overriddenParentClass, purityConfig)) return true
            }
        }
        return false
    }

    /** Checks that [function], expected to follow this annotation's rules, actually does -
     * reports any violations via [messageCollector] (respecting @TestExpectCompileError) and
     * returns the reported messages (empty if valid). */
    abstract fun validate(function: IrFunction, purityConfig: PurityConfig, messageCollector: MessageCollector): List<String>
}
