package yairm210.purity.validation

import org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext
import org.jetbrains.kotlin.cli.common.messages.CompilerMessageSeverity
import org.jetbrains.kotlin.descriptors.DescriptorVisibilities
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.backend.js.utils.parentEnumClassOrNull
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrProperty
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.util.*
import yairm210.purity.PurityConfig
import yairm210.purity.boilerplate.DebugLogger
import yairm210.purity.validation.functionpurity.CheckFunctionPurityVisitor
import yairm210.purity.validation.functionpurity.ExpectedFunctionPurityChecker
import yairm210.purity.validation.functionpurity.FunctionPurity
import yairm210.purity.validation.functionpurity.isStrictlyMoreRestrictiveThan

/** 
 * Iterates over all functions in the IR.
 * For each function, creates a CheckFunctionPurityVisitor to raise errors for that specific function.
 * */
internal class PurityElementTransformer(
    private val debugLogger: DebugLogger,
    private val purityConfig: PurityConfig,
) : IrElementTransformerVoidWithContext() {
    
    // These are created behind the scenes for every class, don't warn for them
    private val autogeneratedFunctions = setOf(
        "equals",
        "hashCode",
        "toString"
    )
    private val enumAutogeneratedFunctions = setOf(
        "values",
        "valueOf",
        "compareTo",
        "clone"
    )
    
    private fun isAutogeneratedFunction(function: IrSimpleFunction): Boolean {
        val name = function.name.asString()
        return autogeneratedFunctions.contains(name) 
                || name.startsWith('<') // auto-generated functions like <init>, <get-name>, <set-name>
                || function.parentEnumClassOrNull != null && (name in enumAutogeneratedFunctions) // Enum values function
                || function.parentClassOrNull?.isData == true && ExpectedFunctionPurityChecker.componentRegex.matches(name) // componentN functions for data classes
                || function.parentClassOrNull?.isData == true && name == "copy" // copy function for data classes

    }
    
    private fun isSuppressed(declaration: IrSimpleFunction): Boolean {
        // Also check overridden functions so a child override inherits suppression from the parent
        return declaration.suppressesPurity()
                || getAllOverriddenFunctions(declaration).any { it.suppressesPurity() }
    }

    override fun visitPropertyNew(declaration: IrProperty): IrStatement {
        if (declaration.visibility != DescriptorVisibilities.PRIVATE && declaration.hasAnnotation(Annotations.Cache)){
            val message = "Variable \"${declaration.name}\" is marked as \"@Cache\", but is public - this annotation is reserved for private variables"
            
            debugLogger.messageCollector.report(
                CompilerMessageSeverity.ERROR, message,
                location = getLocationForExpression(declaration.fileEntry, declaration)
            )
        }
        return super.visitPropertyNew(declaration)
    }
    
    override fun visitSimpleFunction(declaration: IrSimpleFunction): IrStatement {
        if (isAutogeneratedFunction(declaration)) return super.visitSimpleFunction(declaration)

        // Skip interface/abstract functions that are not implemented
        if (declaration.body == null) return super.visitSimpleFunction(declaration)

        if (isSuppressed(declaration)) return super.visitSimpleFunction(declaration)

        val functionDeclaredPurity = when {
            ExpectedFunctionPurityChecker.isMarkedAsPure(declaration, purityConfig) -> FunctionPurity.Pure
            ExpectedFunctionPurityChecker.isReadonly(declaration, purityConfig) -> FunctionPurity.Readonly
            // @InternalStateMutation/@InternalStateAccess are not orthogonal to each other - they're
            // two points on the same read/write restrictiveness lattice as Pure/Readonly (InternalStateAccess
            // strictly more restrictive than InternalStateMutation) - so exactly one is picked here, same
            // as Pure/Readonly above, rather than validating both independently (unlike @ReturnsNewInstance,
            // which is an orthogonal, unrelated property and is validated independently below).
            // A direct annotation on the function itself always wins over one inherited from its class,
            // so a function can deliberately relax (or further restrict) what its class declares.
            declaration.parent !is IrClass -> FunctionPurity.None // local functions can't be isolated-checked for this - see InternalStateMutationValidator/InternalStateAccessValidator
            declaration.hasAnnotation(Annotations.InternalStateAccess) -> FunctionPurity.InternalStateAccess
            declaration.hasAnnotation(Annotations.InternalStateMutation) -> FunctionPurity.InternalStateMutation
            FunctionAnnotations.InternalStateAccess.isExplicitlyMarked(declaration, purityConfig) -> FunctionPurity.InternalStateAccess
            FunctionAnnotations.InternalStateMutation.isExplicitlyMarked(declaration, purityConfig) -> FunctionPurity.InternalStateMutation
            else -> FunctionPurity.None
        }
        val messageCollector = debugLogger.messageCollector

        val visitor = CheckFunctionPurityVisitor(declaration, functionDeclaredPurity, messageCollector, purityConfig)
        declaration.accept(visitor, Unit)

        // @ReturnsNewInstance is an orthogonal, unrelated property - a function can simultaneously be
        // e.g. @Pure AND @ReturnsNewInstance - so it's validated independently of the above
        val returnsNewInstanceMessages = FunctionAnnotations.ReturnsNewInstance.validate(declaration, purityConfig, messageCollector)

        val hasErrored = visitor.hasErrored || returnsNewInstanceMessages.isNotEmpty()

        val actualPurity = visitor.actualFunctionPurity()

        if (visitor.hasExpectCompileErrorAnnotation) { // opposite land - fail is success, success is fail
            // We use hasErrored and not function purity, because there are other kinds of exceptions
            // For example, passing a non-readonly variable to a @Readonly parameter doesn't violate purity, but it is an error!
            if (!hasErrored)
                messageCollector.report(
                    CompilerMessageSeverity.ERROR,
                    "Function \"${declaration.name}\" should fail on purity checks, but succeeds!",
                    location = getLocationForExpression(declaration, declaration)
                )

            return super.visitSimpleFunction(declaration)
        }

        val shouldWarnForPossibleAnnotations =
            actualPurity.isStrictlyMoreRestrictiveThan(functionDeclaredPurity)
                && purityConfig.warnOnPossibleAnnotations
                && !isAutogeneratedFunction(declaration)
                && !declaration.overriddenSymbols.any() // not inherited
                && declaration.parentClassOrNull?.isInterface != true
        
        if (shouldWarnForPossibleAnnotations) {
            // if equal, no message; If less that declared, we already warn for each individual violation
            val message = when (actualPurity) {
                FunctionPurity.Pure -> "Function \"${declaration.name}\" can be marked with @Pure to indicate it is pure"
                FunctionPurity.Readonly -> "Function \"${declaration.name}\" can be marked with @Readonly to indicate it is readonly"
                FunctionPurity.InternalStateAccess -> "Function \"${declaration.name}\" can be marked with @InternalStateAccess to indicate it only reads and writes its own instance-internal state"
                FunctionPurity.InternalStateMutation -> "Function \"${declaration.name}\" can be marked with @InternalStateMutation to indicate it only writes its own instance-internal state"
                else -> throw Exception("Unexpected function purity: $actualPurity")
            }

            debugLogger.messageCollector.report(
                CompilerMessageSeverity.WARNING, message,
                location = getLocationForExpression(declaration, declaration)
            )
        }

        return super.visitSimpleFunction(declaration)
    }

}