name: Generate mkdocs from docs folder
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: write      
  
jobs:
  update-mkdocs:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
